# Generated by Django 3.1 on 2020-08-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_it_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='clock_in',
            new_name='clock_in_time',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='clock_out',
            new_name='clock_out_time',
        ),
    ]
