# Generated by Django 3.1 on 2020-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_it_app', '0002_auto_20200825_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clock_out_time',
            field=models.DateTimeField(),
        ),
    ]
